// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHTF.Context;

namespace SHTF.Migrations
{
    [DbContext(typeof(SHTFListContext))]
    [Migration("20190726221358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SHTF.Context.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("SHTF.Context.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactCatId");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactNote");

                    b.HasKey("ContactId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("SHTF.Context.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FoodAmount");

                    b.Property<int>("FoodCatId");

                    b.Property<bool>("FoodDone");

                    b.Property<string>("FoodName");

                    b.HasKey("FoodId");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("SHTF.Context.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemAmount");

                    b.Property<int>("ItemCatId");

                    b.Property<bool>("ItemDone");

                    b.Property<string>("ItemName");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SHTF.Context.Supply", b =>
                {
                    b.Property<int>("SupplyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SupplyAmount");

                    b.Property<int>("SupplyCatId");

                    b.Property<bool>("SupplyDone");

                    b.Property<string>("SupplyName");

                    b.HasKey("SupplyId");

                    b.ToTable("Supply");
                });
#pragma warning restore 612, 618
        }
    }
}
